apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: dotnet-app:{{IMAGE_TAG}}
        name: dotnet-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}
