apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: dotnet
spec:
  ports:
  - name: "8080"
    nodePort: 30010
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: NodePort
status:
  loadBalancer: {}
