name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set short SHA
      run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ttvone/dotnet-app:${IMAGE_TAG}

    - name: Push image to Docker Hub
      run: docker push ttvone/dotnet-app:${IMAGE_TAG}

    - name: Replace {{IMAGE_TAG}} in k8s/02-deployment.yaml
      run: sed -i "s/{{IMAGE_TAG}}/${IMAGE_TAG}/g" k8s/02-deployment.yaml

    - name: Commit and push updated k8s/02-deployment.yaml
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add k8s/02-deployment.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push